apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: doug-clone
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/doug-clone
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: VERTEX_VDB_DOMAIN
          value: "25224006.europe-west2-98733960248.vdb.vertexai.goog"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: key
        - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
          valueFrom:
            secretKeyRef:
              name: google-credentials
              key: credentials.json
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
